spring.application.name=payment-api
server.port=8080
management.endpoints.web.exposure.include=health,info,metrics,prometheus,threaddump
spring.datasource.url=jdbc:postgresql://localhost:5432/paymentdb
spring.datasource.username=payment
spring.datasource.password=payment
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.properties.spring.json.add.type.headers=false
logging.pattern.level=%5p [%thread]
