spring.application.name=bank-simulator
server.port=8081
management.endpoints.web.exposure.include=health,info,metrics,prometheus,threaddump
spring.datasource.url=jdbc:postgresql://localhost:5432/paymentdb
spring.datasource.username=payment
spring.datasource.password=payment
spring.datasource.hikari.maximum-pool-size=20
spring.kafka.bootstrap-servers=localhost:9092
management.metrics.distribution.percentiles-histogram.http.server.requests=true
